### ISSUE TITLE
Add protractor-cucumber-typescript example!

### ISSUE THREAD

**Issue by igniteram** [angular/protractor-cookbook#13]
Once the globals are removed and protractor-typescript features are more stable(breaking changes) would be sending a PR !

**Comment by cnishina** [comment]
@igniteram 4.0.9 is out... very excited for your PR.

**Comment by igniteram** [comment]
@cnishina has been served with PR https://github.com/angular/protractor-cookbook/pull/14 😄 . I have used @juliemr 's [protractor-demo](http://juliemr.github.io/protractor-demo/) as test app for the test scripts as it has a `title` attribute something I wanted to include in the example scripts!
