### ISSUE TITLE
Including typescript files in specs

### ISSUE THREAD

**Issue by mailmrmanoj** [angular/protractor-cookbook#38]
Can I include spec files (.ts) in specs section of protractor.conf.ts  and  run tests directly without compiling them to .js files ?

**Comment by cnishina** [comment]
Something like? I should probably add these to the typescript example.

```
  specs: [
    './e2e/test-8-1.e2e-spec.ts'
  ],
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e'
    });
  },
```

**Comment by mailmrmanoj** [comment]
Thanks,Got it :-)
